services:
  backend:
    build:
      context: ./backend  # Adjusted to the actual path
      dockerfile: Dockerfile
    container_name: devops-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=devops
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops-frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - frontend

  mysql:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: devops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: devops-prometheus
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: devops-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  grafana_data:
