replicaCount: 1

image:
  repository: my-docker-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - host: myapp.local
      paths: []
  tls: []
