name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline when changes are pushed to the main branch.
  pull_request:
    branches:
      - main  # Triggers pipeline on pull request to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build and push the backend Docker image
    - name: Build backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: dardanrashiti88/devops-platform-stack-backend:latest

    # Build and push the frontend Docker image
    - name: Build frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        tags: dardanrashiti88/devops-platform-stack-frontend:latest

    # Build and push the database Docker image
    - name: Build db Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/db/Dockerfile
        push: true
        tags: dardanrashiti88/devops-platform-stack-db:latest

