name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 of checkout

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3  # Updated to v3 of cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Root directory
        file: ./backend/Dockerfile  # Path to backend Dockerfile
        push: true
        tags: dardanrashiti88/devops-platform-stack-backend:latest

    - name: Build frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Root directory
        file: ./frontend/Dockerfile  # Path to frontend Dockerfile
        push: true
        tags: dardanrashiti88/devops-platform-stack-frontend:latest


