name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build backend image
      run: |
        docker buildx build --file ./docker/backend/Dockerfile --tag dardanrashiti88/devops-platform-stack-backend:latest --push .

    - name: Build database image
      run: |
        docker buildx build --file ./docker/db/Dockerfile --tag dardanrashiti88/devops-platform-stack-db:latest --push .

    - name: Build frontend image
      run: |
        docker buildx build --file ./docker/frontend/Dockerfile --tag dardanrashiti88/devops-platform-stack-frontend:latest --push .
